# Generated by Django 4.2.2 on 2023-06-10 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('menuImage', models.ImageField(blank=True, null=True, upload_to='static/images/foods')),
                ('menuImageUrl', models.CharField(blank=True, max_length=255, null=True)),
                ('ingredients', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.category')),
            ],
        ),
    ]
