# Generated by Django 4.2.2 on 2023-06-12 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_userinfo_user_email'),
        ('food', '0003_cart_menu_ratings_menu_total_sold_cartproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.profile')),
                ('menuName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.menu')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratingScore', models.PositiveIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.profile')),
                ('menuName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.menu')),
            ],
        ),
    ]
