# Generated by Django 4.2.2 on 2023-06-12 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='ratings',
            field=models.CharField(default=0, max_length=155),
        ),
    ]
