# Generated by Django 4.2.2 on 2023-06-15 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='menuName',
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
