# Generated by Django 4.2.2 on 2023-06-15 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_remove_review_menuname_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='remain_star',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
